"""docker-compose call + invariants."""

from __future__ import annotations

import datetime
import hashlib
import json
import os
import re
import subprocess
import sys
from pathlib import Path
from typing import Any

from catraz.paths import asset_root
from catraz.errors import CliError, EXIT_CONFIG


# Semantic service aliases → compose service names (P1: no raw container names).
SERVICES = {
    "agent": "claude-dev-env",
    "warden": "gitlab-warden",
    "proxy": "forward-proxy",
}


def project_name(root: Path) -> str:
    """Stable, globally-unique Compose project name for a sandbox.

    Compose otherwise defaults the project name to the basename of --project-directory,
    which is NOT unique: two sandboxes in same-named dirs (~/work/api and ~/scratch/api)
    would both be project `api`, and their containers/networks/volumes would collide. We
    anchor it to a short hash of the ABSOLUTE root path (unique per location) while keeping
    the basename for readability. Must match Compose's name rule: [a-z0-9][a-z0-9_-]*.
    """
    base = re.sub(r"[^a-z0-9_-]", "-", root.name.lower()).strip("-_") or "proj"
    digest = hashlib.sha256(str(root.resolve()).encode()).hexdigest()[:8]
    return f"catraz-{base}-{digest}"


def _source_cmd(root: Path) -> list[str]:
    """Layered multi-file command — used only to generate resolved.yml (or as fallback).

    auth_mode(root) is called on every compose invocation (up/run/shell/down/ps/…).
    An invalid AUTH_MODE therefore fails fast at every call site, not only on first `up`.
    """
    from catraz.auth import auth_mode

    ar = asset_root()
    cmd = [
        "docker",
        "compose",
        "-f",
        str(ar / "assets/compose/docker-compose.yml"),
        "--project-directory",
        str(root),
        "--project-name",
        project_name(root),
        "--env-file",
        str(root / ".catraz/.env"),
    ]
    cmd += ["-f", str(ar / "assets/compose" / f"auth.{auth_mode(root)}.yml")]
    override = root / ".catraz/compose.override.yml"
    if override.exists():
        cmd += ["-f", str(override)]
    return cmd


# Backward-compat alias — tests that reference base_cmd still work.
base_cmd = _source_cmd


def _resolved_cmd(root: Path) -> list[str]:
    """Command prefix that runs the fully-interpolated resolved.yml."""
    return [
        "docker",
        "compose",
        "-f",
        str(root / ".catraz/compose.resolved.yml"),
        "--project-directory",
        str(root),
        "--project-name",
        project_name(root),
    ]


def _warn_fallback(msg: str) -> None:
    print(f"catraz WARNING: {msg}", file=sys.stderr)


def generate_resolved(root: Path, extra_env: dict[str, str] | None = None) -> bool:
    """Render the effective compose and write .catraz/compose.resolved.yml at mode 0600.

    Runs `docker compose ... --profile remote config` (interpolated, agent stays gated).
    Returns True on success, False on failure (caller falls back to _source_cmd).
    """
    env = dict(
        os.environ, PROJECT_DIR=str(root), CATRAZ_ASSETS=str(asset_root() / "assets")
    )
    if extra_env:
        env.update(extra_env)
    cmd = [*_source_cmd(root), "--profile", "remote", "config"]
    try:
        r = subprocess.run(cmd, env=env, capture_output=True, text=True)
    except FileNotFoundError:
        return False
    if r.returncode != 0:
        return False
    resolved = root / ".catraz/compose.resolved.yml"
    header = (
        "# Auto-generated by catraz — overwritten by state-changing commands.\n"
        "# Debug: docker compose -f .catraz/compose.resolved.yml …\n"
        "# Regenerated per command; host- and catraz-version-specific (not portable).\n"
        "# Secrets are file references, not values.\n"
    )
    content = header + r.stdout
    fd = os.open(str(resolved), os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
    try:
        os.write(fd, content.encode())
    finally:
        os.close(fd)
    return True


def prepare(
    root: Path, *, render: bool, extra_env: dict[str, str] | None = None
) -> list[str]:
    """Return the compose cmd prefix for this handler to use consistently.

    render=True  (up/run/shell/down): write auth fragment + (re)generate resolved.yml.
    render=False (status/logs):       reuse existing resolved.yml; no side effects.
    Falls back to _source_cmd (with a loud warning) when rendering fails.
    """
    if render:
        if generate_resolved(root, extra_env):
            return _resolved_cmd(root)
        _warn_fallback(
            "config render failed — running layered; resolved.yml may be stale"
        )
        return _source_cmd(root)
    if (root / ".catraz/compose.resolved.yml").exists():
        return _resolved_cmd(root)
    return _source_cmd(root)  # read-only before first up → layered, no side effects


def run(
    root: Path,
    args: list[str],
    *,
    prefix: list[str] | None = None,
    capture: bool = False,
    check: bool = True,
    print_only: bool = False,
    extra_env: dict[str, str] | None = None,
    tee: Path | None = None,
) -> subprocess.CompletedProcess[str] | None:
    from catraz.errors import CliError, EXIT_DOCKER

    _prefix = prefix if prefix is not None else _source_cmd(root)
    cmd = [*_prefix, *args]
    if print_only:
        print(" ".join(cmd))
        return None
    # CATRAZ_ASSETS anchors the compose build contexts at the extracted asset cache.
    # Compose resolves relative `context:` paths against --project-directory (the user's
    # repo), so the contexts are absolute via this var instead — see docker-compose.yml.
    env = dict(
        os.environ, PROJECT_DIR=str(root), CATRAZ_ASSETS=str(asset_root() / "assets")
    )
    if extra_env:
        env.update(extra_env)
    if tee is not None:
        # Stream the child's combined output to both our stdout and a durable file.
        # The tee branch cannot honor check= (it never raises on non-zero) — fail loud
        # if a future caller forgets. Today's only caller passes check=False.
        assert not check, "tee path does not support check="
        tee.parent.mkdir(parents=True, exist_ok=True)
        try:
            with open(tee, "wb") as f:
                p = subprocess.Popen(
                    cmd, env=env, stdout=subprocess.PIPE, stderr=subprocess.STDOUT
                )
                # read1 (not read) returns as soon as data is available, preserving live
                # output — read(n) would block until n bytes or EOF.
                assert p.stdout is not None
                stdout = p.stdout
                for chunk in iter(lambda: stdout.read1(65536), b""):  # type: ignore[attr-defined]
                    sys.stdout.buffer.write(chunk)
                    sys.stdout.buffer.flush()
                    f.write(chunk)
                p.wait()
        except FileNotFoundError:
            raise CliError("`docker` not found on PATH", EXIT_DOCKER)
        return subprocess.CompletedProcess(cmd, p.returncode)
    try:
        return subprocess.run(
            cmd, env=env, check=check, capture_output=capture, text=True
        )
    except FileNotFoundError:
        raise CliError("`docker` not found on PATH", EXIT_DOCKER)


def compose_ps(
    root: Path, *, prefix: list[str] | None = None, all: bool = False
) -> list[dict[str, str]]:
    """Return [{Service, State, Health}, …] from `docker compose ps`.

    all=True passes `-a` so stopped containers *and* `run --rm` one-offs (hidden by
    default) are visible. Keep the default False: cmd_status/_wait_healthy/_ensure_infra
    rely on seeing only live service containers."""
    args = ["ps"] + (["-a"] if all else []) + ["--format", "json"]
    r = run(root, args, prefix=prefix, capture=True, check=False)
    if r is None or r.returncode != 0 or not r.stdout.strip():
        return []
    text = r.stdout.strip()
    try:  # some compose versions emit a JSON array, others one object per line
        data = json.loads(text)
        rows = data if isinstance(data, list) else [data]
    except json.JSONDecodeError:
        rows = [json.loads(ln) for ln in text.splitlines() if ln.strip()]
    return rows


def _parse_docker_time(s: str) -> datetime.datetime | None:
    """Parse a docker `StartedAt` timestamp into an aware datetime, or None.

    Python 3.11+ `fromisoformat` accepts arbitrary fractional-second digits (it
    truncates 9-digit nanoseconds to micros) and we normalize a trailing `Z` to an
    explicit UTC offset. requires-python >=3.11, so no manual digit-stripping needed.
    """
    s = s.strip().replace("Z", "+00:00")
    try:
        return datetime.datetime.fromisoformat(s)
    except ValueError:
        return None


def container_started_at(
    root: Path, name_or_id: str, *, prefix: list[str] | None = None
) -> datetime.datetime | None:
    """Container start time via `docker inspect`, or None if unreadable/unparseable.

    Pass the `Name`/`ID` already carried by `compose ps --format json` rows — no
    separate `ps -q` per service. None means "couldn't read it" (caller treats a
    running-but-unknown service as stale, never as up-to-date)."""
    try:
        r = subprocess.run(
            ["docker", "inspect", "-f", "{{.State.StartedAt}}", name_or_id],
            capture_output=True,
            text=True,
        )
    except FileNotFoundError:
        return None
    if r.returncode != 0 or not r.stdout.strip():
        return None
    return _parse_docker_time(r.stdout)


def resolve_service(name: str) -> str:
    from catraz.errors import CliError, EXIT_CONFIG

    if name in SERVICES:
        return SERVICES[name]
    if name in SERVICES.values():
        return name
    raise CliError(
        f"unknown service '{name}' — use one of: {', '.join(SERVICES)}", EXIT_CONFIG
    )


def _rc(r: subprocess.CompletedProcess[str] | None) -> int:
    """Return EXIT_OK if r succeeded, EXIT_GENERAL otherwise.

    Used by cmd_down and cmd_logs only. cmd_run propagates claude's own exit
    code directly (2, 130, 137, …) — do NOT route cmd_run through _rc."""
    from catraz.errors import EXIT_OK, EXIT_GENERAL

    return EXIT_OK if r and r.returncode == 0 else EXIT_GENERAL


def assert_real_dirs(root: Path) -> None:
    for p in (root, root / ".catraz"):
        if p.is_symlink():
            raise CliError(
                f"{p} is a symlink — bind source must be a real dir", EXIT_CONFIG
            )


def _env_keys(agent: dict[str, Any]) -> set[str]:
    env = agent.get("environment") or {}
    if isinstance(env, list):
        return {e.split("=", 1)[0] for e in env}
    return set(env.keys())


def _good_tmpfs(v: dict[str, Any]) -> bool:
    """True when v is the /workspace/.catraz tmpfs with the correct mode and size.

    compose config normalizes mode 0700 → 448 (0o700 == 448). Always assert the
    numeric value so a future serializer that mangles it fails the check loudly.
    """
    if v.get("type") != "tmpfs" or v.get("target") != "/workspace/.catraz":
        return False
    opts = v.get("tmpfs") or {}
    return opts.get("mode") == 448 and "size" in opts


def assert_invariants(root: Path, *, prefix: list[str] | None = None) -> None:
    _prefix = prefix if prefix is not None else _source_cmd(root)
    r = run(
        root,
        ["--profile", "remote", "config", "--format", "json"],
        prefix=_prefix,
        capture=True,
        check=False,
    )
    if r is None or r.returncode != 0:
        raise CliError(
            "docker compose config failed (cannot verify trust boundary)", EXIT_CONFIG
        )
    cfg = json.loads(r.stdout)
    if not cfg.get("networks", {}).get("agent-net", {}).get("internal"):
        raise CliError("invariant: agent-net is not internal", EXIT_CONFIG)
    agent = cfg["services"]["claude-dev-env"]
    if any(k.startswith("GITLAB_") and k.endswith("_TOKEN") for k in _env_keys(agent)):
        raise CliError("invariant: agent carries a GITLAB_*_TOKEN", EXIT_CONFIG)
    if agent.get("privileged") or "SYS_ADMIN" in (agent.get("cap_add") or []):
        raise CliError("invariant: agent is privileged / CAP_SYS_ADMIN", EXIT_CONFIG)
    # The base image inherits setuid/setgid binaries from Ubuntu (passwd, su, mount, …).
    # no-new-privileges makes them inert at execve, so they cannot be used for privilege
    # escalation. This must hold non-bypassably (it is also what lets `doctor base` stop
    # warning about those binaries) — normalize `:`/`=` separators across compose versions.
    sec = {o.replace("=", ":") for o in (agent.get("security_opt") or [])}
    if "no-new-privileges:true" not in sec:
        raise CliError(
            "invariant: agent missing no-new-privileges (setuid escalation)",
            EXIT_CONFIG,
        )
    vols = agent.get("volumes", [])
    if not any(_good_tmpfs(v) for v in vols):
        raise CliError(
            "invariant: tmpfs shadow on /workspace/.catraz missing or misconfigured "
            "(expected type=tmpfs, mode=448, size)",
            EXIT_CONFIG,
        )
