"""Commit 11.4 — generate .catraz/compose.resolved.yml (0600) and run it.

No Docker — monkeypatches compose.subprocess.run.
"""
import stat
from pathlib import Path
from typing import Any
import pytest

from catraz import compose
from catraz.paths import asset_root


# ── helpers ──────────────────────────────────────────────────────────────────

def _make_root(tmp_path: Path) -> Path:
    root = tmp_path / "proj"
    root.mkdir()
    cat = root / ".catraz"
    cat.mkdir()
    (cat / "config").mkdir()
    (cat / "config" / "warden.toml").write_text('allowed_projects = ["group/sub/proj"]\n')
    (cat / ".env").write_text("AUTH_MODE=subscription\n")
    return root


FAKE_CONFIG_OUTPUT = """\
services:
  gitlab-warden:
    image: fake-warden
networks:
  agent-net:
    internal: true
"""


def _fake_subprocess_success(output: str = FAKE_CONFIG_OUTPUT) -> Any:
    """Return a fake subprocess module where run() succeeds with the given stdout."""
    class FakeProc:
        returncode: int = 0
        stdout: str = output
        stderr: str = ""
    class FakeSub:
        @staticmethod
        def run(cmd: Any, **k: Any) -> FakeProc:
            return FakeProc()
    return FakeSub()


def _fake_subprocess_fail() -> Any:
    class FakeProc:
        returncode: int = 1
        stdout: str = ""
        stderr: str = "error"
    class FakeSub:
        @staticmethod
        def run(cmd: Any, **k: Any) -> FakeProc:
            return FakeProc()
    return FakeSub()


# ── (a) success: file written at 0600, header present, prepare returns resolved prefix ──

def test_generate_resolved_writes_file_at_0600(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    root = _make_root(tmp_path)
    monkeypatch.setattr(compose, "subprocess", _fake_subprocess_success())
    ok = compose.generate_resolved(root)
    assert ok
    resolved = root / ".catraz/compose.resolved.yml"
    assert resolved.exists()
    assert stat.S_IMODE(resolved.stat().st_mode) == 0o600
    content = resolved.read_text()
    assert "Auto-generated by catraz" in content
    assert FAKE_CONFIG_OUTPUT in content


def test_prepare_render_true_returns_resolved_prefix(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    root = _make_root(tmp_path)
    monkeypatch.setattr(compose, "subprocess", _fake_subprocess_success())
    prefix = compose.prepare(root, render=True)
    resolved_path = str(root / ".catraz/compose.resolved.yml")
    assert resolved_path in prefix
    assert "--project-directory" in prefix
    assert "--project-name" in prefix


# ── (b) render RC≠0: returns _source_cmd prefix + warning ──

def test_prepare_render_fail_returns_source_cmd(tmp_path: Path, monkeypatch: pytest.MonkeyPatch, capsys: pytest.CaptureFixture[str]) -> None:
    root = _make_root(tmp_path)
    monkeypatch.setattr(compose, "subprocess", _fake_subprocess_fail())
    prefix = compose.prepare(root, render=True)
    # Should return the layered source cmd (not resolved)
    resolved_path = str(root / ".catraz/compose.resolved.yml")
    assert resolved_path not in prefix
    assert "docker-compose.yml" in " ".join(prefix)
    # Warning should have been printed to stderr
    captured = capsys.readouterr()
    assert "WARNING" in captured.err or "fallback" in captured.err.lower() or "stale" in captured.err


# ── (c) render=False with existing resolved.yml: returns resolved prefix ──

def test_prepare_render_false_existing_resolved(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    root = _make_root(tmp_path)
    resolved = root / ".catraz/compose.resolved.yml"
    resolved.write_text("# existing\n")

    prefix = compose.prepare(root, render=False)
    assert str(resolved) in prefix


# ── (d) render=False, no resolved.yml: returns layered source, no side effects ──

def test_prepare_render_false_no_resolved(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    root = _make_root(tmp_path)
    # No resolved.yml
    prefix = compose.prepare(root, render=False)
    assert str(root / ".catraz/compose.resolved.yml") not in prefix
    assert "docker-compose.yml" in " ".join(prefix)


# ── (e) _source_cmd always includes the auth asset (unconditional -f) ──

def test_source_cmd_includes_auth_asset_subscription(tmp_path: Path) -> None:
    root = _make_root(tmp_path)
    cmd = compose._source_cmd(root)
    ar = str(asset_root() / "assets" / "compose" / "auth.subscription.yml")
    assert ar in cmd


def test_source_cmd_includes_auth_asset_api_key(tmp_path: Path) -> None:
    root = _make_root(tmp_path)
    (root / ".catraz" / ".env").write_text("AUTH_MODE=api_key\n")
    cmd = compose._source_cmd(root)
    ar = str(asset_root() / "assets" / "compose" / "auth.api_key.yml")
    assert ar in cmd


# ── (f) leak guard: resolved.yml is always written at 0600 ──

def test_resolved_written_at_0600_even_with_sensitive_output(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    """Even if the config stdout contains sensitive-looking strings, resolved.yml stays 0600."""
    sensitive_output = "ANTHROPIC_API_KEY: sk-ant-secretvalue\nGITLAB: glpat-xxx\n"
    root = _make_root(tmp_path)
    monkeypatch.setattr(compose, "subprocess", _fake_subprocess_success(sensitive_output))
    compose.generate_resolved(root)
    resolved = root / ".catraz/compose.resolved.yml"
    assert resolved.exists()
    assert stat.S_IMODE(resolved.stat().st_mode) == 0o600
